#!/bin/bash
cd /home/strien/ve.direct-python
python -u -m vedirect --influx=localhost --database=container --port=/dev/ttyUSB0 | tee -a  /home/strien/vedirect.log
#python -u -m vedirect  --port=/dev/ttyUSB0
